# Generated by Django 3.1.5 on 2021-05-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_sqft', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=200)),
                ('lease_number', models.CharField(max_length=200)),
                ('lease_type', models.CharField(max_length=200)),
                ('tenant_name', models.CharField(max_length=200)),
                ('unit_number', models.PositiveIntegerField()),
                ('unit_sqft', models.PositiveIntegerField()),
                ('lease_begin_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('annual_rent_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('annual_rent', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['lease_type'],
            },
        ),
    ]
